### PR TITLE
Fix #4 dynamically pick up region for principal

### LINKED ISSUE #4: Plugin fails on non us-east-1 deployments
PR pending

```
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: myFunctionSubscriptionFilter
     - Could not execute the lambda function. Make sure you
     have given CloudWatch Logs permission to execute your
     function..

  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your stack: myFunctionSubscriptionFilter -  Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function..
```

### PR DESCRIPTION
**Pull request by maxcan**
Fixes #4

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ class Plugin {
         };
 
         Object.freeze(filterBaseStatement); // Make it immutable
-
+        let principal = "logs." + this.serverless.service.provider.region + ".amazonaws.com";
```
Comment (johncmckim) [inline src/index.js]: Can you please update this to use `const` and string templates?

``` javascript
const principal = `logs.${this.serverless.service.provider.region}.amazonaws.com`;
```

If you can do that it will be GTM.

Comment (maxcan) [reply src/index.js]: done

**Comment by johncmckim** [comment]
Thanks @maxcan !
